export const projectData = [
    {
        id: "1",
        name: "Quizzical",
        shortDescription: "Quizzical is a five-question general knowledge quiz, using the Open Trivia Database API.",
        longDescription: "Quizzical is a five-question general knowledge quiz, using the Open Trivia Database API. I chose React for this project to create reusable components for each question and answer, manage and track state throughout the quiz, and leverage useEffect to execute code based on dependencies.",
        img1: "/assets/project-imgs/quizzical-1.jpg",
        img1Alt: "A screenshot of Quzzical displaying 5 general knowledge questions and 4 answer options.",
        img2: "/assets/project-imgs/quizzical-2.jpg",
        img2Alt: "A graphic of a question mark above the text Quizzical",
        img3: "/assets/project-imgs/quizzical-3.jpg",
        img3Alt: "A screenshot of Quizzical displaying 5 answered general knowledge questions. Four questions are answered correctly and one incorrectly.",
        thumbnailImg: "/assets/project-imgs/quizzical-thumbnail.jpg",
        skills: ["React", "JavaScript", "HTML", "CSS", "APIs"],
        githubUrl: "https://github.com/louiseka/quizzical",
        liveUrl: "https://louiseka.github.io/quizzical/",
        gridPosition: "one",
        cardLayout: "normal"

    },
    {
        id: "2",
        name: "Film Watchlist",
        shortDescription: "A Film Watchlist, enabling users to search for films they want to watch.",
        longDescription: "This Film Watchlist leverages the Open Movie Database API, enabling users to search for films they want to watch. Users can add films to a watchlist or remove them as needed, with all data saved to and removed from their local storage. I chose JavaScript for this project for easy API handling, use of localStorage, and to enhance user experience.",
        img1: "/assets/project-imgs/filmwatchlist-1.jpg",
        img1Alt: "A screen shot of Film Watchlist. Search is for 'Marvel' films and relevant results are displayed underneath with a descriptionl, review rating, and a film poster thumbnail.",
        img2: "/assets/project-imgs/filmwatchlist-2.jpg",
        img2Alt: "Text displays 'Find your film' with a film camera icon above.",
        img3: "/assets/project-imgs/filmwatchlist-3.jpg",
        img3Alt: "A screenshot of films saved to 'My Watchlist'.",
        thumbnailImg: "/assets/project-imgs/filmwatchlist-thumbnail.jpg",
        skills: ["JavaScript", "APIs", "HTML", "CSS"],
        githubUrl: "https://github.com/louiseka/film-watchlist",
        liveUrl: "https://louiseka.github.io/film-watchlist/",
        gridPosition: "two",
        cardLayout: "wide"
    },
    {
        id: "3",
        name: "Colour Scheme Generator",
        shortDescription: "Users can select a colour and a colour scheme from a dropdown menu to generate a palette.",
        longDescription: "I've created a Colour Scheme Picker using 'The Color API.' Users can select a colour and a colour scheme from a dropdown menu to generate a palette of five colours based on the chosen scheme.I chose to use JavaScript, so that I could respond to user’s inputs via event listeners, retrieve data from the The Color API efficiently with fetch(), and to manipulate the DOM to display the generated palettes. ",
        img1: "/assets/project-imgs/colour-1.jpg",
        img1Alt: "A screenshot of a generated colour scheme for the theme 'Complement'. Each colour block displays the associated hex codes underneath.",
        img2: "/assets/project-imgs/colour-2.jpg",
        img2Alt: "Text displays 'Colour Scheme Generator' with an icon of a rainbow colour wheel above.",
        img3: "/assets/project-imgs/colour-3.jpg",
        img3Alt: "A screenshot of the hex code colour picker used to generate your chosen themed palette.",
        thumbnailImg: "/assets/project-imgs/colour-thumbnail.jpg",
        skills: ["JavaScript", "APIs", "HTML", "CSS"],
        githubUrl: "https://github.com/louiseka/colour-scheme",
        liveUrl: "https://louiseka.github.io/colour-scheme/",
        gridPosition: "three",
        cardLayout: "wide"
    },
    {
        id: "4",
        name: "Recipe Roulette",
        shortDescription: "A random meal generator to help you choose tonight's dinner.",
        longDescription: "Recipe Roulette' is a random meal generator. Choose a cuisine, click 'Get Random Recipe,' and a recipe will appear in a pop-up with an image and a link to the full recipe. Don't like it? Close the pop-up and try again! I used JavaScript for this project to make use of a flexible dataset, to be able to use Math.random to generate random recipes from an array, and to handle user interactions easily. ",
        img1: "/assets/project-imgs/roulette-1.jpg",
        img1Alt: "A screenshot of Recipe Roulette, showcasing seven different cuisines for users to choose from, along with a button to generate a random recipe.",
        img2: "/assets/project-imgs/roulette-2.jpg",
        img2Alt: "Text displays 'Recipe Roulette,' accompanied by a graphic of a fork and knife.",
        img3: "/assets/project-imgs/roulette-3.jpg",
        img3Alt: "A screenshot of Recipe Roulette, showing the generated random recipe in a pop out.",
        thumbnailImg: "/assets/project-imgs/roulette-thumbnail.jpg",
        skills: ["JavaScript", "HTML", "CSS"],
        githubUrl: "https://github.com/louiseka/recipe-roulette",
        liveUrl: "https://louiseka.github.io/recipe-roulette/",
        gridPosition: "four",
        cardLayout: "normal"
    },

    {
        id: "5",
        name: "Dish Diaries",
        shortDescription: "A solo project that was created as a final presentation piece for Code First Girls Kickstarter course.",
        longDescription: "Dish Diaries was a solo project that was created as a final presentation piece for Code First Girls Coding Kickstarter Web Development course. Dish Diaries is an accessible alternative to those keyword and ad stuffed recipe websites that we have all experienced. ",
        img1: "/assets/project-imgs/dishdiaries-1.jpg",
        img1Alt: "A screenshot of Dish Diaries homepage.",
        img2: "/assets/project-imgs/dishdiaries-2.jpg",
        img2Alt: "Text displays 'Dish Diairies' accompanied by a graphic of a fork and knife.",
        img3: "/assets/project-imgs/dishdiaries-3.jpg",
        img3Alt: "A screenshot of a Chocolate Chip Muffins recipe.",
        thumbnailImg: "/assets/project-imgs/dishdiaries-thumbnail.jpg",
        skills: ["HTML", "CSS", "Bootstrap", "JavaScript"],
        githubUrl: "https://github.com/louiseka/CFG-Project",
        liveUrl: "https://louiseka.github.io/CFG-Project/",
        gridPosition: "five",
        cardLayout: "normal"
    },
    {
        id: "6",
        name: "BoredBot",
        shortDescription: "A random idea generator for when you're bored.",
        longDescription: "BoredBot is an idea generator powered by the 'Bored API'. Click the button to generate a random idea. Don't like the idea? Just keep clicking until you find one you love! I chose JavaScript for this project to handle button clicks with event listeners, fetch data efficiently from the Bored API, and dynamically manipulate the DOM to display the generated ideas.",
        img1: "/assets/project-imgs/boredbot-1.jpg",
        img1Alt: "A screenshot of BoredBot with a button to click to generate a random idea.",
        img2: "/assets/project-imgs/boredbot-2.jpg",
        img2Alt: "Text displays 'BoredBot', accompanied by a graphic of a lightbulb.",
        img3: "/assets/project-imgs/boredbot-3.jpg",
        img3Alt: "A screenshot of a generated idea and a button to click to generate another random idea.",
        thumbnailImg: "/assets/project-imgs/boredbot-thumbnail.jpg",
        skills: ["JavaScript", "APIs", "HTML", "CSS"],
        githubUrl: "https://github.com/louiseka/idea-generator",
        liveUrl: "https://louiseka.github.io/idea-generator/",
        gridPosition: "six",
        cardLayout: "normal"
    },

] 